In [1]:
import pandas as pd
import numpy as np
import matplotlib as mt
import seaborn as sns

In [2]:
df = pd.read_csv("NCRB_Table_1A.1.csv")

In [3]:
df.head()

,Sl. No.,State/UT,2020,2021,2022,Mid-Year Projected Population (in Lakhs) (2022),Rate of Cognizable Crimes (IPC) (2022),Chargesheeting Rate (2022)
0,1,Andhra Pradesh,188997,179611,158547,530.3,299.0,86.5
1,2,Arunachal Pradesh,2244,2626,2308,15.5,148.8,47.2
2,3,Assam,111558,119883,59315,354.9,167.1,32.6
3,4,Bihar,194698,186006,211079,1255.3,168.1,75.4
4,5,Chhattisgarh,65216,70519,73822,299.5,246.5,80.4

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 8 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Sl. No.                                          39 non-null     object
 1   State/UT                                         39 non-null     object
 2   2020                                             39 non-null     int64
 3   2021                                             39 non-null     int64
 4   2022                                             39 non-null     int64
 5   Mid-Year Projected Population (in Lakhs) (2022)  39 non-null     float64
 6   Rate of Cognizable Crimes (IPC) (2022)           39 non-null     float64
 7   Chargesheeting Rate (2022)                       39 non-null     float64
dtypes: float64(3), int64(3), object(2)
memory usage: 2.6+ KB

In [5]:
df.describe()

,2020,2021,2022,Mid-Year Projected Population (in Lakhs) (2022),Rate of Cognizable Crimes (IPC) (2022),Chargesheeting Rate (2022)
count,3.900000e+01,3.900000e+01,3.900000e+01,39.000000,39.000000,39.000000
mean,3.272582e+05,2.817969e+05,2.739522e+05,1061.343590,257.238462,67.423077
std,9.083960e+05,7.682254e+05,7.453848e+05,2992.018951,246.044296,20.240208
min,1.070000e+02,8.900000e+01,6.400000e+01,0.700000,45.400000,10.400000
25%,2.727000e+03,2.555000e+03,2.985000e+03,19.200000,144.850000,56.750000
50%,6.521600e+04,7.051900e+04,5.931500e+04,299.700000,189.800000,74.900000
75%,1.939885e+05,2.002790e+05,2.024960e+05,691.700000,292.550000,81.400000
max,4.254356e+06,3.663360e+06,3.561379e+06,13797.500000,1424.100000,96.000000