In [6]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [7]:
df = pd.read_csv("commodity_futures.csv")

In [9]:
df.head(10)

,Date,NATURAL GAS,GOLD,WTI CRUDE,BRENT CRUDE,SOYBEANS,CORN,COPPER,SILVER,LOW SULPHUR GAS OIL,...,ZINC,ULS DIESEL,NICKEL,WHEAT,SUGAR,GASOLINE,COFFEE,LEAN HOGS,HRW WHEAT,COTTON
0,2000-01-03,NaN,NaN,NaN,NaN,456.50,200.75,NaN,NaN,NaN,...,1237.50,NaN,8446.0,247.50,6.10,NaN,116.50,55.975,274.25,51.07
1,2000-01-04,2.176,283.7,25.55,24.39,464.25,203.00,0.8480,5.375,213.50,...,1215.00,67.78,8314.0,247.25,5.77,NaN,116.25,55.625,274.00,50.73
2,2000-01-05,2.168,282.1,24.91,23.73,469.25,203.00,0.8565,5.210,213.00,...,1209.25,66.55,8307.0,249.75,5.81,NaN,118.60,55.075,276.25,51.56
3,2000-01-06,2.196,282.4,24.78,23.62,468.00,203.75,0.8530,5.167,211.25,...,1212.00,66.28,8252.0,248.50,5.77,NaN,116.85,55.175,275.00,52.08
4,2000-01-07,2.173,282.9,24.22,23.09,471.50,207.00,0.8540,5.195,205.25,...,1209.25,64.75,8174.0,251.75,5.84,NaN,114.15,55.625,277.75,53.96
5,2000-01-10,2.216,282.7,24.67,23.73,466.25,208.50,0.8465,5.190,196.00,...,1196.75,64.72,8130.0,253.50,5.83,NaN,117.55,55.650,279.75,53.56
6,2000-01-11,2.260,284.4,25.77,24.62,467.00,207.25,0.8435,5.195,201.50,...,1185.00,66.75,8052.5,253.75,5.67,NaN,117.80,56.025,280.00,54.18
7,2000-01-12,2.244,283.7,26.28,24.81,472.50,215.50,0.8660,5.143,201.50,...,1195.75,68.47,8191.0,258.75,5.45,NaN,118.95,54.800,285.75,53.72
8,2000-01-13,2.252,285.1,26.69,24.98,481.75,220.75,0.8565,5.153,208.25,...,1194.00,69.28,8107.0,263.50,5.49,NaN,118.55,54.825,290.00,54.75
9,2000-01-14,2.322,284.9,28.02,25.47,485.50,219.00,0.8625,5.150,213.75,...,1195.75,73.81,8125.0,265.00,5.45,NaN,112.55,56.150,293.00,55.12

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6092 entries, 0 to 6091
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 6092 non-null   object
 1   NATURAL GAS          6083 non-null   float64
 2   GOLD                 6082 non-null   float64
 3   WTI CRUDE            6083 non-null   float64
 4   BRENT CRUDE          6090 non-null   float64
 5   SOYBEANS             6083 non-null   float64
 6   CORN                 6084 non-null   float64
 7   COPPER               6083 non-null   float64
 8   SILVER               6079 non-null   float64
 9   LOW SULPHUR GAS OIL  6090 non-null   float64
 10  LIVE CATTLE          6084 non-null   float64
 11  SOYBEAN OIL          6079 non-null   float64
 12  ALUMINIUM            6045 non-null   float64
 13  SOYBEAN MEAL         6082 non-null   float64
 14  ZINC                 6046 non-null   float64
 15  ULS DIESEL           6083 non-null   float64
 16  NICKEL               6046 non-null   float64
 17  WHEAT                6078 non-null   float64
 18  SUGAR                6083 non-null   float64
 19  GASOLINE             4601 non-null   float64
 20  COFFEE               6080 non-null   float64
 21  LEAN HOGS            6084 non-null   float64
 22  HRW WHEAT            6078 non-null   float64
 23  COTTON               6079 non-null   float64
dtypes: float64(23), object(1)
memory usage: 1.1+ MB

In [11]:
df.describe

<bound method NDFrame.describe of             Date  NATURAL GAS    GOLD  WTI CRUDE  BRENT CRUDE  SOYBEANS  \
0     2000-01-03          NaN     NaN        NaN          NaN    456.50
1     2000-01-04        2.176   283.7      25.55        24.39    464.25
2     2000-01-05        2.168   282.1      24.91        23.73    469.25
3     2000-01-06        2.196   282.4      24.78        23.62    468.00
4     2000-01-07        2.173   282.9      24.22        23.09    471.50
...          ...          ...     ...        ...          ...       ...
6087  2023-07-31        2.634  1970.5      81.80        85.56   1445.75
6088  2023-08-01        2.560  1940.7      81.37        84.91   1446.75
6089  2023-08-02        2.477  1937.4      79.49        83.20   1429.75
6090  2023-08-03        2.565  1932.0      81.55        85.14   1428.75
6091  2023-08-04        2.581  1939.0      82.34        85.90   1441.00

        CORN  COPPER  SILVER  LOW SULPHUR GAS OIL  ...     ZINC  ULS DIESEL  \
0     200.75     NaN     NaN                  NaN  ...  1237.50         NaN
1     203.00  0.8480   5.375               213.50  ...  1215.00       67.78
2     203.00  0.8565   5.210               213.00  ...  1209.25       66.55
3     203.75  0.8530   5.167               211.25  ...  1212.00       66.28
4     207.00  0.8540   5.195               205.25  ...  1209.25       64.75
...      ...     ...     ...                  ...  ...      ...         ...
6087  504.00  4.0080  24.972               877.25  ...  2571.31      299.09
6088  497.00  3.9085  24.326               911.50  ...  2574.80      302.34
6089  488.25  3.8435  23.872               884.50  ...  2486.50      300.43
6090  480.75  3.8995  23.697               899.50  ...  2494.00      307.49
6091  482.50  3.8610  23.675               903.25  ...      NaN      306.23

       NICKEL   WHEAT  SUGAR  GASOLINE  COFFEE  LEAN HOGS  HRW WHEAT  COTTON
0      8446.0  247.50   6.10       NaN  116.50     55.975     274.25   51.07
1      8314.0  247.25   5.77       NaN  116.25     55.625     274.00   50.73
2      8307.0  249.75   5.81       NaN  118.60     55.075     276.25   51.56
3      8252.0  248.50   5.77       NaN  116.85     55.175     275.00   52.08
4      8174.0  251.75   5.84       NaN  114.15     55.625     277.75   53.96
...       ...     ...    ...       ...     ...        ...        ...     ...
6087  22127.0  665.75  24.11    292.90  164.65    104.125     812.75   85.44
6088  22189.0  652.25  24.39    287.30  164.55    103.675     804.50   86.87
6089  21379.0  640.00  24.20    277.58  166.95    102.675     787.00   85.08
6090  21402.0  627.00  24.02    276.47  164.75    101.000     767.50   85.28
6091      NaN  632.00  23.78    277.45  162.55    100.700     760.25   85.48

[6092 rows x 24 columns]>

In [ ]:
6092/365

16.69041095890411

In [19]:
df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values("Date").reset_index(drop=True)

In [20]:
df.head()

,index,Date,NATURAL GAS,GOLD,WTI CRUDE,BRENT CRUDE,SOYBEANS,CORN,COPPER,SILVER,...,ZINC,ULS DIESEL,NICKEL,WHEAT,SUGAR,GASOLINE,COFFEE,LEAN HOGS,HRW WHEAT,COTTON
0,0,2000-01-03,NaN,NaN,NaN,NaN,456.50,200.75,NaN,NaN,...,1237.50,NaN,8446.0,247.50,6.10,NaN,116.50,55.975,274.25,51.07
1,1,2000-01-04,2.176,283.7,25.55,24.39,464.25,203.00,0.8480,5.375,...,1215.00,67.78,8314.0,247.25,5.77,NaN,116.25,55.625,274.00,50.73
2,2,2000-01-05,2.168,282.1,24.91,23.73,469.25,203.00,0.8565,5.210,...,1209.25,66.55,8307.0,249.75,5.81,NaN,118.60,55.075,276.25,51.56
3,3,2000-01-06,2.196,282.4,24.78,23.62,468.00,203.75,0.8530,5.167,...,1212.00,66.28,8252.0,248.50,5.77,NaN,116.85,55.175,275.00,52.08
4,4,2000-01-07,2.173,282.9,24.22,23.09,471.50,207.00,0.8540,5.195,...,1209.25,64.75,8174.0,251.75,5.84,NaN,114.15,55.625,277.75,53.96

In [21]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month

In [25]:
df.head()

,index,Date,NATURAL GAS,GOLD,WTI CRUDE,BRENT CRUDE,SOYBEANS,CORN,COPPER,SILVER,...,NICKEL,WHEAT,SUGAR,GASOLINE,COFFEE,LEAN HOGS,HRW WHEAT,COTTON,Year,Month
0,0,2000-01-03,NaN,NaN,NaN,NaN,456.50,200.75,NaN,NaN,...,8446.0,247.50,6.10,NaN,116.50,55.975,274.25,51.07,2000,1
1,1,2000-01-04,2.176,283.7,25.55,24.39,464.25,203.00,0.8480,5.375,...,8314.0,247.25,5.77,NaN,116.25,55.625,274.00,50.73,2000,1
2,2,2000-01-05,2.168,282.1,24.91,23.73,469.25,203.00,0.8565,5.210,...,8307.0,249.75,5.81,NaN,118.60,55.075,276.25,51.56,2000,1
3,3,2000-01-06,2.196,282.4,24.78,23.62,468.00,203.75,0.8530,5.167,...,8252.0,248.50,5.77,NaN,116.85,55.175,275.00,52.08,2000,1
4,4,2000-01-07,2.173,282.9,24.22,23.09,471.50,207.00,0.8540,5.195,...,8174.0,251.75,5.84,NaN,114.15,55.625,277.75,53.96,2000,1

In [30]:
print(df.isna().sum())

index                     0
Date                      0
NATURAL GAS               9
GOLD                     10
WTI CRUDE                 9
BRENT CRUDE               2
SOYBEANS                  9
CORN                      8
COPPER                    9
SILVER                   13
LOW SULPHUR GAS OIL       2
LIVE CATTLE               8
SOYBEAN OIL              13
ALUMINIUM                47
SOYBEAN MEAL             10
ZINC                     46
ULS DIESEL                9
NICKEL                   46
WHEAT                    14
SUGAR                     9
GASOLINE               1491
COFFEE                   12
LEAN HOGS                 8
HRW WHEAT                14
COTTON                   13
Year                      0
Month                     0
dtype: int64

In [28]:
df_ffill = df.ffill()

In [32]:
print(df_ffill.isna().sum())

index                     0
Date                      0
NATURAL GAS               1
GOLD                      1
WTI CRUDE                 1
BRENT CRUDE               1
SOYBEANS                  0
CORN                      0
COPPER                    1
SILVER                    1
LOW SULPHUR GAS OIL       1
LIVE CATTLE               0
SOYBEAN OIL               0
ALUMINIUM                 1
SOYBEAN MEAL              0
ZINC                      0
ULS DIESEL                1
NICKEL                    0
WHEAT                     0
SUGAR                     0
GASOLINE               1483
COFFEE                    0
LEAN HOGS                 0
HRW WHEAT                 0
COTTON                    0
Year                      0
Month                     0
dtype: int64

In [33]:
df_clean = df.ffill().bfill()

In [35]:
print(df_clean.isna().sum())

index                  0
Date                   0
NATURAL GAS            0
GOLD                   0
WTI CRUDE              0
BRENT CRUDE            0
SOYBEANS               0
CORN                   0
COPPER                 0
SILVER                 0
LOW SULPHUR GAS OIL    0
LIVE CATTLE            0
SOYBEAN OIL            0
ALUMINIUM              0
SOYBEAN MEAL           0
ZINC                   0
ULS DIESEL             0
NICKEL                 0
WHEAT                  0
SUGAR                  0
GASOLINE               0
COFFEE                 0
LEAN HOGS              0
HRW WHEAT              0
COTTON                 0
Year                   0
Month                  0
dtype: int64